version: 0.2
# Defining default values for all jobs
defaults: &defaults
env:
  variables:
    SFDX_USE_GENERIC_UNIX_KEYCHAIN: "true"

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm install sfdx-cli --global
      #- npm update --global sfdx-cli
  build:
    commands:
      - echo Build started on `14/05/2020`
      - echo $salesforceInstanceURL
      - echo $salesforceUserName
      - echo $salesforceClientId
      #- sfdx --help
      #- sfdx force:auth:logout --targetusername balajibondar@gmail.com.cicd
      - sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVyq3tLvSSXPZetZl3qbVbXU9EanjeRiVjbfUuab7ULGYnFCgt1Shpu37vRZ9sA5KwshFfhK --jwtkeyfile ./server.key --username balajibondar@gmail.com.cicd --instanceurl https://login.salesforce.com
      #- sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVyq3tLvSSXPZetZl3qbVbXU9EanjeRiVjbfUuab7ULGYnFCgt1Shpu37vRZ9sA5KwshFfhK --jwtkeyfile ./buildfiles/server.key --username balajibondar@gmail.com.cicd --instanceurl https://cicddemodevhub-dev-ed.lightning.force.com/
      #- sfdx force:mdapi:deploy -l RunLocalTests -c -d ./force-app/main/default/ -u SIT -w 10
      
