version: 0.2
# Defining default values for all jobs
defaults: &defaults
env:
  variables:
    SFDX_USE_GENERIC_UNIX_KEYCHAIN: "true"

phases:
  pre_build:
    commands:
      - echo pre_build phase,installation started...
      #- npm install sfdx-cli --global
      #- npm update --global sfdx-cli
      - curl -fL https://getcli.jfrog.io | sh
  build:
    commands:
      - echo Build started...
      - echo $salesforceInstanceURL
      - echo $salesforceUserName
      - echo $salesforceClientId
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SRC_DIR
      
      #- sfdx --help
      #- sfdx force:auth:jwt:grant --clientid $salesforceClientId --jwtkeyfile ./server.key --username $salesforceUserName --instanceurl $salesforceInstanceURL -a SIT
      #- sfdx force:mdapi:deploy -l RunLocalTests -c -d ./force-app/main/default/ -u SIT -w 10
      - ./jfrog rt config --url https://sdc.jfrog.io/artifactory/ --user salesforce-ci --password AKCp5fTQixdiS5iECcdfqYug9kkW2CJUrb9GJz3MechLrfemcasce5cJXxG1RW1fLDd94rw5d --interactive=false
      #- ./jfrog rt u /deply /germs --build-name=MyBuild --build-number=12345
artifacts:
  files:
    - deploy/*
    - ./jfrog rt u /deply /germs --build-name=MyBuild --build-number=12345
  discard-paths: yes
